### PR TITLE
Fixes to support cross-compilation

### PR DESCRIPTION
**Pull request by mathias-arm**

### CODE REVIEW

**Comment by egrimley-arm** [comment]
The change looks fine, but doesn't it work better to do this as a Veracruz PR and manually push the `rust-mbedtls` change after the Veracruz PR is merged?

**Comment by mathias-arm** [comment]
The Veracruz PR will come later, the code that needs this is in a branch that is not ready to be merged.

**Comment by egrimley-arm** [comment]
Might it be worth proposing these changes upstream? We were almost at the point of being able to use the unmodified upstream `rust-mbedtls` (apart from on IceCap).

**Review by egrimley-arm — APPROVED** [review]
This seems fine. You can just manually push it if we want to avoid the unnecessary complexity of merge nodes.

**Pull request merged**
