### PR TITLE
Workaround for Nitro's RNG

### PR DESCRIPTION
**Pull request by gbryant-arm**
Replace `getrandom` syscall with a read from `/dev/urandom`.
This is a quick fix for https://github.com/veracruz-project/veracruz/issues/507.
In the long term, using Veracruz's platform services to provide portable RNG sounds like a better idea.

### CODE REVIEW

**Comment by egrimley-arm** [comment]
Can this be made conditional on Nitro?

I would guess that this would not work on IceCap.

**Comment by egrimley-arm** [comment]
This does not build on IceCap.

**Comment by egrimley-arm** [comment]
> In the long term, using Veracruz's platform services to provide portable RNG sounds like a better idea.

Making `getrandom` work on Nitro by initialising the kernel's entropy might be an even better idea?

**Comment by egrimley-arm** [comment]
Hang on! If `getrandom` doesn't work, that probably means that the entropy you're getting from `/dev/urandom` is insecure, so why bother reading from it at all? Why not just return all zeroes, which would definitely be portable?

**Comment by egrimley-arm** [comment]
Perhaps a good way to do this would be to create a new "feature" of `mbedtls` called `fake_random` rather than anything referring to Nitro, arrange for it to be passed through to `mbedtls-sys-auto`, and make `build.rs` conditionally define `VERACRUZ_FAKE_RANDOM` when compiling `mbedtls_hardware_poll.c`. When that symbol is defined the function could just return zeroes.

I don't think there's any point in reading from `/dev/urandom` if `getrandom` is not working.

We could then build `mbedtls` with `fake_random` only on Nitro.

I'm not totally familiar with the right way to do those `Cargo.toml` feature things.

**Comment by egrimley-arm** [comment]
Another thing: I'm not sure that creating PRs on `rust-mbedtls` is a good way to do things. It's probably better to do this with a PR on `veracruz`.

**Comment by mathias-arm** [comment]
Superseded by #6

**Pull request closed without merging**
